name: fruits_hub_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.3
  dartz: ^0.10.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.0
  skeletonizer: ^1.4.3
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Cairo # This is the name you'll use in your code
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600

  assets:
    - assets/icons/

flutter_assets:
  assets_path:
    - assets/icons/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
flutter_intl:
  enabled: true
