// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkavFPtGE0vqpPTKenIMDzBfMDgAVL5w',
    appId: '1:996259284948:web:7dcada12b0c85805903841',
    messagingSenderId: '996259284948',
    projectId: 'fruit-hub-647ce',
    authDomain: 'fruit-hub-647ce.firebaseapp.com',
    storageBucket: 'fruit-hub-647ce.firebasestorage.app',
    measurementId: 'G-E4MTLJXP3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8UxnXt8bzCYY15UoDp0UkT6zJsjMJMx8',
    appId: '1:996259284948:android:9bc0cf8809596c26903841',
    messagingSenderId: '996259284948',
    projectId: 'fruit-hub-647ce',
    storageBucket: 'fruit-hub-647ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Rz3yDSdHZs1EUjgsZlzamkOEXWeUvKw',
    appId: '1:996259284948:ios:1592a64924ddf71a903841',
    messagingSenderId: '996259284948',
    projectId: 'fruit-hub-647ce',
    storageBucket: 'fruit-hub-647ce.firebasestorage.app',
    androidClientId: '996259284948-4sn9uqhnuqqgqdodbsclqeo0k0vqdsrj.apps.googleusercontent.com',
    iosClientId: '996259284948-odl9vbi7dsjfiqt1cur9rgia0ga5cll4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Rz3yDSdHZs1EUjgsZlzamkOEXWeUvKw',
    appId: '1:996259284948:ios:1592a64924ddf71a903841',
    messagingSenderId: '996259284948',
    projectId: 'fruit-hub-647ce',
    storageBucket: 'fruit-hub-647ce.firebasestorage.app',
    androidClientId: '996259284948-4sn9uqhnuqqgqdodbsclqeo0k0vqdsrj.apps.googleusercontent.com',
    iosClientId: '996259284948-odl9vbi7dsjfiqt1cur9rgia0ga5cll4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdkavFPtGE0vqpPTKenIMDzBfMDgAVL5w',
    appId: '1:996259284948:web:e2f309cd9db643f2903841',
    messagingSenderId: '996259284948',
    projectId: 'fruit-hub-647ce',
    authDomain: 'fruit-hub-647ce.firebaseapp.com',
    storageBucket: 'fruit-hub-647ce.firebasestorage.app',
    measurementId: 'G-EPB7S414KN',
  );
}
